# Generated by Django 5.2.5 on 2025-08-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
